apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
data:
  my-config.txt: |
    [mysqld]
    wsrep_on=ON
    wsrep_provider=/usr/lib/galera/libgalera_smm.so
    wsrep_cluster_address=gcomm://mariadb-cluster-0.mariadb-cluster,mariadb-cluster-1.mariadb-cluster,mariadb-cluster-2.mariadb-cluster
    wsrep_cluster_name=mariadb-galera-cluster
    wsrep_node_address=gcomm://$(hostname -s).mariadb-cluster
    wsrep_sst_method=rsync
    wsrep_node_name=$(hostname -s)
    binlog_format=row
    default_storage_engine=InnoDB
    innodb_autoinc_lock_mode=2
    bind-address=0.0.0.0